# AWS CodeBuild buildspec to deploy the Ghost MySQL Database CDK

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - cd aws-app-resources
      - sudo npm install -g aws-cdk
      - pip install --upgrade aws-cdk.core
      - pip install --upgrade -r requirements.txt
      - export CDK_DEPLOY_ACCOUNT=$(aws sts get-caller-identity | jq -r '.Account')
  build:
    commands:
      - echo CDK Deploy started on `date`
      - cdk deploy
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Deploy successfully completed on `date`