apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ghost
  namespace: ghost
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:505070718513:certficate/c564fed3-d2d5-42ed-a0e7-0d593665483d
    alb.ingress.kubernetes.io/success-codes: 200,302
    external-dns.alpha.kubernetes.io/hostname: ghost.jasonumiker.com  
  labels:
    app: ghost
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ghost
              servicePort: 2368
